# Generated by Django 4.0.5 on 2022-07-03 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='followers',
            new_name='following',
        ),
    ]
